/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'yamashiro-r' at '16/09/05 21:31' with Gradle 2.13
 *
 * @author yamashiro-r, @date 16/09/05 21:31
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
